import "./modules/attributable.test.js";
import "./modules/heritable.test.js";
import "./modules/observable_roles/event_handlers_map.test.js";
import "./modules/observable_roles/subscriber.test.js";
import "./modules/observable_roles/publisher.test.js";
import "./modules/observable_roles/event_lock.test.js";
import "./modules/validatable.test.js";
import "./modules/component_validation.test.js";
import "./modules/component_dom.test.js";
import "./modules/component_heritage.test.js";
import "./modules/auto_show_hide.test.js";
import "./utils/map_utils.test.js";
import "./utils/type_checker.test.js";
import "./utils/mixin.test.js";
import "./utils/cookies.test.js";
import "./utils/linked_hash_map.test.js";
import "./i18n.test.js";
import "./logmaster.test.js";
import "./ajax_request.test.js";
import "./position_manager.test.js";
import "./component.test.js";

// Components
import "./components/root_component.test.js";
import "./components/button_component.test.js";
import "./components/checkbox_component.test.js";
import "./components/form_field_component.test.js";
import "./components/numeric_form_field_component.test.js";
import "./components/modal_window_component.test.js";
import "./components/dialog_window_component.test.js";
import "./components/radio_button_component.test.js";
import "./components/hint_component.test.js";
import "./components/simple_notification_component.test.js";
import "./components/select_component.test.js";
import "./components/confirmable_button_component.test.js";
import "./components/context_menu_component.test.js";

// Behaviors
import "./behaviors/component_behaviors.test.js";
import "./behaviors/button_component_behaviors.test.js";
import "./behaviors/checkbox_component_behaviors.test.js";
import "./behaviors/form_field_component_behaviors.test.js";
import "./behaviors/modal_window_component_behaviors.test.js";
import "./behaviors/hint_component_behaviors.test.js";
import "./behaviors/simple_notification_component_behaviors.test.js";
import "./behaviors/select_component_behaviors.test.js";
import "./behaviors/context_menu_component_behaviors.test.js";
